# Generated by Django 6.0.4 on 2026-04-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('projects_count', models.CharField(default='0+', max_length=10)),
                ('experience_years', models.CharField(default='0+', max_length=10)),
                ('certifications_count', models.CharField(default='0+', max_length=10)),
                ('technologies_count', models.CharField(default='0+', max_length=10)),
            ],
        ),
    ]
