# Generated by Django 6.0.4 on 2026-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
